# Generated by Django 5.1.3 on 2024-11-08 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=100)),
                ('credit_hours', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_initial', models.CharField(blank=True, max_length=1, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('employment_type', models.CharField(choices=[('REGULAR', 'Regular'), ('COS', 'Contract of Service'), ('Not Specified', 'Not Specified')], default='Not Specified', max_length=15)),
                ('college_id', models.IntegerField()),
                ('qualified_course', models.JSONField(default=list)),
                ('availability_days', models.JSONField(default=list)),
                ('availability_times', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'instructors',
            },
        ),
        migrations.CreateModel(
            name='TeachingLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor')),
            ],
            options={
                'db_table': 'teaching_load',
            },
        ),
    ]
